[default]
SECRET_KEY = "123456"
EXTENSIONS = [ "aulatap311.ext.login:init_app", "aulatap311.ext.database:init_app", "aulatap311.blueprints.cadastro.cadastro:init_app",]
SQLALCHEMY_DATABASE_URI = "sqlite:////home/felipe/Projetos/aulatap311/instance/db.sqlite3"
SQLALCHEMY_TRACK_MODIFICATIONS = false
