"""muitos para muitos

Revision ID: 28d949ca3725
Revises: 476f364c1010
Create Date: 2021-11-05 13:51:40.690010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d949ca3725'
down_revision = '476f364c1010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_noticia'))
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    op.create_table('noticia_tag',
    sa.Column('noticia_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticia.id'], name=op.f('fk_noticia_tag_noticia_id_noticia')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_noticia_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('noticia_id', 'tag_id', name=op.f('pk_noticia_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticia_tag')
    op.drop_table('tag')
    op.drop_table('noticia')
    # ### end Alembic commands ###
