"""muitos para muitos novo igual doc

Revision ID: 7648e5705312
Revises: 28d949ca3725
Create Date: 2021-11-05 14:03:16.307880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7648e5705312'
down_revision = '28d949ca3725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticatag',
    sa.Column('noticia_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticia.id'], name=op.f('fk_noticatag_noticia_id_noticia')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_noticatag_tag_id_tag')),
    sa.PrimaryKeyConstraint('noticia_id', 'tag_id', name=op.f('pk_noticatag'))
    )
    op.drop_table('noticia_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticia_tag',
    sa.Column('noticia_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticia.id'], name='fk_noticia_tag_noticia_id_noticia'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='fk_noticia_tag_tag_id_tag'),
    sa.PrimaryKeyConstraint('noticia_id', 'tag_id', name='pk_noticia_tag')
    )
    op.drop_table('noticatag')
    # ### end Alembic commands ###
